FROM python:3.10-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV DJANGO_ENV production

RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential libpq-dev nodejs npm

COPY requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt

COPY pomodoro /pomodoro

WORKDIR /pomodoro

RUN python manage.py check --deploy --fail-level WARNING

CMD ["gunicorn", "pomodoro.wsgi", "--bind", "0.0.0.0:3000"]
