FROM python:3.10-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential libpq-dev nodejs npm

COPY requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt

# Mounted volume for live loading
WORKDIR /pomodoro

RUN python3 /pomodoro/manage.py tailwind install -v

ENTRYPOINT ["python3"] 
CMD ["manage.py", "runserver", "0.0.0.0:3000"]

